# Generated by Django 6.0.1 on 2026-01-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_service_servicefeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
