# Generated by Django 6.0.1 on 2026-01-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_service_description_alter_service_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class (e.g. fas fa-bolt)', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class (e.g. fas fa-industry)', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
