# Generated by Django 6.0.1 on 2026-01-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_service_description_alter_service_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='FontAwesome icon class (e.g. fas fa-bolt)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
