# Generated by Django 6.0.1 on 2026-01-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
