# Generated by Django 6.0.1 on 2026-01-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_aboutsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='icon',
        ),
    ]
