# Generated by Django 6.0.1 on 2026-01-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_aboutsection_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
