# Generated by Django 6.0.1 on 2026-01-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_aboutsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
